### ISSUE TITLE
lxml

### ISSUE THREAD

**Issue by LaurentBerger** [coa-project/pycoa#100]
Hi,
I follow [install procedure](https://github.com/coa-project/pycoa/wiki/Install#installation-by-hand) on windows.
I tried 
`import coa.front as cf`
I have got an error about lxml
I solved it : 
`pip install lxml`

Is lxml missing in your list?

**Comment by tjbtjbtjb** [comment]
Hi,
Well, no, `lxml` is not missing in our list, I 've just re-checked. Nevertheless, it appears that `pandas`, when reading HTML, may need this lib, and it may not be present on some systems. See for example [https://stackoverflow.com/questions/44954802/python-importerror-lxml-not-found-please-install-it](https://stackoverflow.com/questions/44954802/python-importerror-lxml-not-found-please-install-it).
To confirm this hypothesis, could you send us the typical error message you get ? We would prefer that dependencies work anyway. We may need to add `xml` "by hand" in our list.
Tristan

**Comment by LaurentBerger** [comment]
that's the error

```
Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import coa.front as cf
Traceback (most recent call last):
  File "F:\Program Files\Python\lib\site-packages\coa\display.py", line 110, in get_geodata
    info = coge.GeoInfo()
  File "F:\Program Files\Python\lib\site-packages\coa\geo.py", line 329, in __init__
    self._gm=GeoManager()
  File "F:\Program Files\Python\lib\site-packages\coa\geo.py", line 70, in __init__
    self._gr=GeoRegion()
  File "F:\Program Files\Python\lib\site-packages\coa\geo.py", line 562, in __init__
    p_m49=pd.read_html(get_local_from_url(self._source_dict["UN_M49"],0))[1]
  File "F:\Program Files\Python\lib\site-packages\pandas\util\_decorators.py", line 299, in wrapper
    return func(*args, **kwargs)
  File "F:\Program Files\Python\lib\site-packages\pandas\io\html.py", line 1085, in read_html
    return _parse(
  File "F:\Program Files\Python\lib\site-packages\pandas\io\html.py", line 889, in _parse
    parser = _parser_dispatch(flav)
  File "F:\Program Files\Python\lib\site-packages\pandas\io\html.py", line 846, in _parser_dispatch
    raise ImportError("lxml not found, please install it")
ImportError: lxml not found, please install it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\Program Files\Python\lib\site-packages\coa\front.py", line 63, in <module>
    _db,_cocoplot = coco.DataBase.factory(_whom) # initialization with default
  File "F:\Program Files\Python\lib\site-packages\coa\covid19.py", line 303, in factory
    datab = DataBase(db_name)
  File "F:\Program Files\Python\lib\site-packages\coa\covid19.py", line 51, in __init__
    self.set_display(self.db)
  File "F:\Program Files\Python\lib\site-packages\coa\covid19.py", line 308, in set_display
    self.codisp = codisplay.CocoDisplay(db)
  File "F:\Program Files\Python\lib\site-packages\coa\display.py", line 94, in __init__
    self.location_geometry = self.get_geodata()
  File "F:\Program Files\Python\lib\site-packages\coa\display.py", line 125, in get_geodata
    raise CoaTypeError('What data base are you looking for ?')
coa.error.CoaTypeError: What data base are you looking for ?
In :
```

**Comment by tjbtjbtjb** [comment]
Ok, then it's really coming from `pandas`, which should ask to install `lxml` to work properly. 
I do not know why it's not coming from by default.

I think we will add the dependency _by hand_ to avoid such troubles in the next release.

Thanks for your feedback. 

Cheers.
